/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Benchmarks Endpoint */
        get: operations["list_benchmarks_endpoint_api_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_benchmarks_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_benchmarks_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_benchmarks_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_benchmarks_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_api_cameras_get"];
        put?: never;
        /** Create Camera */
        post: operations["create_camera_api_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera */
        get: operations["get_camera_api_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /** Delete Camera */
        delete: operations["delete_camera_api_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        /** Update Camera */
        patch: operations["update_camera_api_cameras__camera_id__patch"];
        trace?: never;
    };
    "/api/cameras/{camera_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Camera */
        post: operations["close_camera_api_cameras__camera_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{camera_id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open Camera */
        post: operations["open_camera_api_cameras__camera_id__open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cameras/{camera_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Status */
        get: operations["get_camera_status_api_cameras__camera_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cameras */
        get: operations["get_cameras_api_devices_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/network": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Network */
        post: operations["probe_network_api_devices_network_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/serial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Serial Ports */
        get: operations["get_serial_ports_api_devices_serial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inference Sessions */
        get: operations["list_inference_sessions_api_inference_get"];
        put?: never;
        /** Start Inference */
        post: operations["start_inference_api_inference_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Inference Session */
        get: operations["get_inference_session_api_inference__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/{session_id}/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Inference Command */
        post: operations["set_inference_command_api_inference__session_id__command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/{session_id}/deadman": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Inference Deadman */
        post: operations["set_inference_deadman_api_inference__session_id__deadman_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inference/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Inference */
        post: operations["stop_inference_api_inference__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Policies */
        get: operations["list_policies_api_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/policies/{repo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_api_policies__repo_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_api_recordings_get"];
        put?: never;
        /** Start Recording */
        post: operations["start_recording_api_recordings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recording */
        get: operations["get_recording_api_recordings__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Recording */
        post: operations["stop_recording_api_recordings__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Robots */
        get: operations["list_robots_api_robots_get"];
        put?: never;
        /** Create Robot */
        post: operations["create_robot_api_robots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Robot */
        get: operations["get_robot_api_robots__robot_id__get"];
        put?: never;
        post?: never;
        /** Delete Robot */
        delete: operations["delete_robot_api_robots__robot_id__delete"];
        options?: never;
        head?: never;
        /** Update Robot */
        patch: operations["update_robot_api_robots__robot_id__patch"];
        trace?: never;
    };
    "/api/robots/{robot_id}/calibrate/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ack Calibration */
        post: operations["ack_calibration_api_robots__robot_id__calibrate_ack_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/calibrate/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Calibration */
        post: operations["cancel_calibration_api_robots__robot_id__calibrate_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/calibrate/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Calibration */
        post: operations["start_calibration_api_robots__robot_id__calibrate_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/calibrate/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calibrate Status */
        get: operations["calibrate_status_api_robots__robot_id__calibrate_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Calibration */
        get: operations["latest_calibration_api_robots__robot_id__calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect Robot */
        post: operations["connect_robot_api_robots__robot_id__connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect Robot */
        post: operations["disconnect_robot_api_robots__robot_id__disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/robots/{robot_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Robot Status */
        get: operations["get_robot_status_api_robots__robot_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Offer */
        post: operations["post_offer_api_streams_offer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats Batch */
        get: operations["get_stats_batch_api_streams_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{session_id}/ice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Ice */
        post: operations["post_ice_api_streams__session_id__ice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{session_id}/keyframe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Keyframe */
        post: operations["post_keyframe_api_streams__session_id__keyframe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{session_id}/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Quality */
        patch: operations["patch_quality_api_streams__session_id__quality_patch"];
        trace?: never;
    };
    "/api/streams/{session_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_streams__session_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/streams/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Stop */
        post: operations["post_stop_api_streams__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teleops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teleops */
        get: operations["list_teleops_api_teleops_get"];
        put?: never;
        /** Create Teleop */
        post: operations["create_teleop_api_teleops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teleops/{teleop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Teleop */
        get: operations["get_teleop_api_teleops__teleop_id__get"];
        put?: never;
        post?: never;
        /** Delete Teleop */
        delete: operations["delete_teleop_api_teleops__teleop_id__delete"];
        options?: never;
        head?: never;
        /** Update Teleop */
        patch: operations["update_teleop_api_teleops__teleop_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckAccepted */
        AckAccepted: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
        };
        /**
         * BenchmarkInfo
         * @description One entry in the ``list_benchmarks`` response.
         */
        BenchmarkInfo: {
            /** Config Type */
            config_type: string;
            /** Env Name */
            env_name: string;
            /** Fps */
            fps: number;
            /** Task */
            task?: string | null;
        };
        /** BenchmarkListResponse */
        BenchmarkListResponse: {
            /** Benchmarks */
            benchmarks: components["schemas"]["BenchmarkInfo"][];
        };
        /** BenchmarkRunList */
        BenchmarkRunList: {
            /** Runs */
            runs: components["schemas"]["BenchmarkRunSummary"][];
        };
        /**
         * BenchmarkRunSummary
         * @description Point-in-time view of a run. Returned from REST + embedded in WS events.
         */
        BenchmarkRunSummary: {
            /** Completed At */
            completed_at?: string | null;
            /** Current Episode */
            current_episode: number;
            /** Env Name */
            env_name: string;
            /** Episodes */
            episodes: number;
            /** Error */
            error?: {
                [key: string]: string;
            } | null;
            /** Last Reward */
            last_reward?: number | null;
            /** Policy Refs */
            policy_refs: string[];
            /** Progress */
            progress: number;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Seed */
            seed?: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "cancelled" | "failed";
            /** Steps Total */
            steps_total: number;
            /** Storage Dir */
            storage_dir: string;
            /** Task */
            task?: string | null;
        };
        /** BenchmarkStartRequest */
        BenchmarkStartRequest: {
            /** Env Name */
            env_name: string;
            /**
             * Episodes
             * @default 3
             */
            episodes: number;
            /** Policy Refs */
            policy_refs?: string[];
            /** Seed */
            seed?: number | null;
            /** Task */
            task?: string | null;
        };
        /** CalibrationAckRequest */
        CalibrationAckRequest: {
            /** Session Id */
            session_id: string;
            /** Step Id */
            step_id: string;
        };
        /** CalibrationCancelRequest */
        CalibrationCancelRequest: {
            /** Session Id */
            session_id: string;
        };
        /**
         * CalibrationConflict
         * @description Response body for 409 conflicts (FE reads ``existing_session_id``/``current_step_id``).
         */
        CalibrationConflict: {
            /** Current Step Id */
            current_step_id?: string | null;
            /** Detail */
            detail: string;
            /** Existing Session Id */
            existing_session_id?: string | null;
        };
        /** CalibrationStartResponse */
        CalibrationStartResponse: {
            /** Robot Type */
            robot_type: string;
            /** Session Id */
            session_id: string;
            /** Step Ids */
            step_ids: string[];
            /** Total Steps */
            total_steps: number;
        };
        /** CalibrationStatusResponse */
        CalibrationStatusResponse: {
            /** Awaiting User Input */
            awaiting_user_input: boolean;
            /** Progress */
            progress: number;
            /** Robot Type */
            robot_type: string;
            /** Session Id */
            session_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Step Id */
            step_id: string;
            /** Step Index */
            step_index: number;
            /** Total Steps */
            total_steps: number;
        };
        /**
         * CalibrationSummary
         * @description Persisted summary of the last completed calibration.
         */
        CalibrationSummary: {
            /** Calibration Id */
            calibration_id: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Error */
            error?: {
                [key: string]: string;
            } | null;
            /**
             * Result
             * @enum {string}
             */
            result: "ok" | "error" | "cancelled";
            /** Robot Type */
            robot_type: string;
            /** Step Ids */
            step_ids: string[];
        };
        /** CameraCreateRequest */
        CameraCreateRequest: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "opencv" | "realsense" | "network";
            /** Codec Hint */
            codec_hint?: string | null;
            /** Fps */
            fps: number;
            /** Height */
            height: number;
            /** Name */
            name: string;
            source: components["schemas"]["CameraSource"];
            /** Width */
            width: number;
        };
        /** CameraDiscoveryResponse */
        CameraDiscoveryResponse: {
            /** Cameras */
            cameras: components["schemas"]["CameraInfo"][];
            /**
             * Realsense Available
             * @description False when pyrealsense2 is not importable; the realsense list is then empty.
             */
            realsense_available: boolean;
        };
        /** CameraEntry */
        CameraEntry: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "opencv" | "realsense" | "network";
            /**
             * Codec Hint
             * @description Optional encoder hint for WebRTC (e.g. 'h264', 'vp9').
             */
            codec_hint?: string | null;
            /** Fps */
            fps: number;
            /** Height */
            height: number;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Name */
            name: string;
            source: components["schemas"]["CameraSource"];
            /** Width */
            width: number;
        };
        /** CameraInfo */
        CameraInfo: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "opencv" | "realsense";
            default_profile?: components["schemas"]["CameraStreamProfile"];
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * @description Stable identifier: device path for OpenCV, serial for RealSense.
             */
            id: string;
            /**
             * Index
             * @description OpenCV numeric index when applicable.
             */
            index?: number | null;
            /** Name */
            name?: string | null;
            /**
             * Path
             * @description Filesystem device path (Linux only).
             */
            path?: string | null;
        };
        /**
         * CameraSource
         * @description Where the camera frames come from.
         *
         *     Exactly one of ``path`` / ``index`` / ``url`` should be populated
         *     (enforced at the service layer, not here — keeping the model
         *     permissive simplifies JSON round-trips during edits).
         */
        CameraSource: {
            /**
             * Index
             * @description OpenCV device index.
             */
            index?: number | null;
            /**
             * Path
             * @description Filesystem device path (/dev/video0).
             */
            path?: string | null;
            /**
             * Url
             * @description RTSP/HTTP stream URL or realsense serial.
             */
            url?: string | null;
        };
        /** CameraStatus */
        CameraStatus: {
            /**
             * Frames Served
             * @default 0
             */
            frames_served: number;
            /** Last Error */
            last_error?: string | null;
            /**
             * Online
             * @default false
             */
            online: boolean;
            /** Opened At */
            opened_at?: string | null;
            /**
             * Subscriber Count
             * @default 0
             */
            subscriber_count: number;
        };
        /** CameraStreamProfile */
        CameraStreamProfile: {
            /** Format */
            format?: string | null;
            /** Fps */
            fps?: number | null;
            /** Height */
            height?: number | null;
            /** Width */
            width?: number | null;
        };
        /** CancelAccepted */
        CancelAccepted: {
            /**
             * Cancelled
             * @default true
             * @constant
             */
            cancelled: true;
        };
        /** CommandRequest */
        CommandRequest: {
            /** Text */
            text: string;
        };
        /** DeadmanRequest */
        DeadmanRequest: {
            /** Held */
            held: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthFlags */
        HealthFlags: {
            /**
             * Fake Devices
             * @default false
             */
            fake_devices: boolean;
            /**
             * Fake Policy
             * @default false
             */
            fake_policy: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            flags: components["schemas"]["HealthFlags"];
            /** Python */
            python: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Uptime Seconds */
            uptime_seconds: number;
            /** Version */
            version: string;
        };
        /**
         * IceRequest
         * @description Browser trickle payload. ``candidate=""`` signals end-of-candidates.
         */
        IceRequest: {
            /**
             * Candidate
             * @default
             */
            candidate: string;
            /** Sdpmlineindex */
            sdpMLineIndex?: number | null;
            /** Sdpmid */
            sdpMid?: string | null;
        };
        /**
         * InferenceSession
         * @description Public view of an inference session for HTTP responses.
         */
        InferenceSession: {
            /**
             * Deadman Held
             * @default false
             */
            deadman_held: boolean;
            /**
             * Deadman Required
             * @default false
             */
            deadman_required: boolean;
            /** Dry Run */
            dry_run: boolean;
            /** Error */
            error?: string | null;
            /** Fps */
            fps: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Latency Ms */
            last_latency_ms?: number | null;
            /** Max Action Magnitude */
            max_action_magnitude?: number | null;
            /** Repo Id */
            repo_id: string;
            /**
             * Robot Id
             * Format: uuid
             */
            robot_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "running" | "stopping" | "stopped" | "failed";
            /**
             * Step
             * @default 0
             */
            step: number;
            /** Stopped At */
            stopped_at?: string | null;
            /**
             * Suppressed Steps
             * @default 0
             */
            suppressed_steps: number;
            /** Task Description */
            task_description: string;
        };
        /** KeyframeResponse */
        KeyframeResponse: {
            /** Senders Signalled */
            senders_signalled: number;
            /** Session Id */
            session_id: string;
        };
        /**
         * NetworkConnection
         * @description TCP/UDP hardware link (e.g. UR7e RTDE, arbitrary network robots).
         */
        NetworkConnection: {
            /**
             * Auth
             * @description Optional auth material (username/password/token). Never logged.
             */
            auth?: {
                [key: string]: string;
            } | null;
            /**
             * Extra
             * @description Protocol-specific kwargs (e.g. rtde frequency). Adapter forwards them.
             */
            extra?: {
                [key: string]: unknown;
            };
            /**
             * Host
             * @description Hostname or IP of the robot controller.
             */
            host: string;
            /**
             * Kind
             * @default network
             * @constant
             */
            kind: "network";
            /**
             * Port
             * @description TCP/UDP port.
             */
            port: number;
            /**
             * Protocol
             * @description Network protocol flavor. 'rtde' is UR, 'fci' is Franka, etc.
             * @enum {string}
             */
            protocol: "rtde" | "fci" | "xmlrpc" | "websocket" | "custom";
        };
        /** NetworkProbeRequest */
        NetworkProbeRequest: {
            /** Host */
            host: string;
            /** Port */
            port?: number | null;
            /**
             * Protocol
             * @description Optional protocol hint. When omitted the port default is used (rtde=30004, fci=10001).
             */
            protocol?: ("rtde" | "fci" | "tcp") | null;
            /**
             * Timeout Ms
             * @default 1000
             */
            timeout_ms: number;
        };
        /** NetworkProbeResponse */
        NetworkProbeResponse: {
            /** Error */
            error?: string | null;
            /** Host */
            host: string;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Port */
            port: number;
            /**
             * Protocol
             * @enum {string}
             */
            protocol: "rtde" | "fci" | "tcp";
            /** Reachable */
            reachable: boolean;
        };
        /** OfferRequest */
        OfferRequest: {
            /**
             * Camera Id
             * @description Registry camera identifier under the robot
             */
            camera_id: string;
            /**
             * Robot Id
             * @description Registry robot identifier
             */
            robot_id: string;
            /**
             * Sdp
             * @description Browser-generated SDP offer payload
             */
            sdp: string;
            /**
             * Type
             * @description SDP type, always 'offer' from the browser
             * @default offer
             */
            type: string;
        };
        /** OfferResponse */
        OfferResponse: {
            /** Applied Codecs */
            applied_codecs: string[];
            /** Sdp */
            sdp: string;
            /** Session Id */
            session_id: string;
            /** Type */
            type: string;
        };
        /**
         * PolicyDescriptor
         * @description Summary of a locally cached policy checkpoint.
         */
        PolicyDescriptor: {
            /** Action Features */
            action_features?: {
                [key: string]: unknown;
            } | null;
            /** Last Modified */
            last_modified?: string | null;
            /** Num Parameters */
            num_parameters?: number | null;
            /** Observation Features */
            observation_features?: {
                [key: string]: unknown;
            } | null;
            /** Policy Type */
            policy_type: string;
            /** Repo Id */
            repo_id: string;
            /** Root */
            root: string;
            /**
             * Supports Language
             * @default false
             */
            supports_language: boolean;
        };
        /** QualityRequest */
        QualityRequest: {
            /** Bitrate Kbps */
            bitrate_kbps?: number | null;
            /** Fps */
            fps?: number | null;
            /** Height */
            height?: number | null;
            /** Width */
            width?: number | null;
        };
        /** QualityResponse */
        QualityResponse: {
            /** Bitrate Kbps */
            bitrate_kbps: number | null;
            /** Fps */
            fps: number | null;
            /** Height */
            height: number | null;
            /** Width */
            width: number | null;
        };
        /**
         * RecordingSession
         * @description Lightweight view of a recording session for HTTP responses.
         */
        RecordingSession: {
            /** Dataset Name */
            dataset_name: string;
            /** Dataset Path */
            dataset_path: string;
            /**
             * Disk Bytes
             * @default 0
             */
            disk_bytes: number;
            /**
             * Drop Count
             * @default 0
             */
            drop_count: number;
            /** Episode Index */
            episode_index?: number | null;
            /** Error */
            error?: string | null;
            /** Fps */
            fps: number;
            /**
             * Frames Captured
             * @default 0
             */
            frames_captured: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Robot Id
             * Format: uuid
             */
            robot_id: string;
            /**
             * Saved
             * @default false
             */
            saved: boolean;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Status
             * @enum {string}
             */
            status: "starting" | "recording" | "stopping" | "saved" | "discarded" | "failed";
            /** Stopped At */
            stopped_at?: string | null;
            /** Task Description */
            task_description: string;
        };
        /**
         * RobotCreateRequest
         * @description Shape accepted by ``POST /api/robots``.
         *
         *     Intentionally omits ``id`` so that clients cannot pin UUIDs; the
         *     registry generates them. Everything else mirrors :class:`RobotEntry`.
         */
        RobotCreateRequest: {
            /** Cameras */
            cameras?: string[];
            /** Connection */
            connection: components["schemas"]["SerialConnection"] | components["schemas"]["NetworkConnection"];
            /** Image Ref */
            image_ref?: string | null;
            /** Name */
            name: string;
            /** Robot Type */
            robot_type: string;
            /** Teleop */
            teleop?: string | null;
        };
        /**
         * RobotEntry
         * @description User-declared robot inventory item (persisted to registry.json).
         *
         *     ``robot_type`` is deliberately str (not Literal) so unknown types
         *     round-trip cleanly. ``KnownRobotType`` is exported for the frontend
         *     Add-Robot dropdown and for the adapter factory's dispatch table.
         */
        RobotEntry: {
            /**
             * Cameras
             * @description Referenced CameraEntry.id values.
             */
            cameras?: string[];
            /** Connection */
            connection: components["schemas"]["SerialConnection"] | components["schemas"]["NetworkConnection"];
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Image Ref
             * @description Static asset path for the UI card (e.g. /resources/so-101.png).
             */
            image_ref?: string | null;
            /** Name */
            name: string;
            /**
             * Robot Type
             * @description lerobot Robot kind. See KnownRobotType for well-known values.
             */
            robot_type: string;
            /**
             * Teleop
             * @description Optional bound TeleopEntry.id.
             */
            teleop?: string | null;
        };
        /** RobotStatus */
        RobotStatus: {
            /** Connected At */
            connected_at?: string | null;
            /** Last Error */
            last_error?: string | null;
            /**
             * Online
             * @default false
             */
            online: boolean;
        };
        /**
         * SerialConnection
         * @description USB-serial hardware link (e.g. SO-101 follower over Feetech).
         */
        SerialConnection: {
            /**
             * Baudrate
             * @description Serial baud. None = adapter picks the motor-bus default.
             */
            baudrate?: number | null;
            /**
             * Kind
             * @default serial
             * @constant
             */
            kind: "serial";
            /**
             * Model Opts
             * @description Opaque kwargs forwarded to the lerobot Robot constructor.
             */
            model_opts?: {
                [key: string]: unknown;
            };
            /**
             * Port
             * @description Stable device path (e.g. /dev/serial/by-id/usb-..., or COM7 on Windows). The frontend picks from the Task #4 device-discovery list.
             */
            port: string;
        };
        /** SerialDiscoveryResponse */
        SerialDiscoveryResponse: {
            /** Ports */
            ports: components["schemas"]["SerialPortInfo"][];
        };
        /** SerialPortInfo */
        SerialPortInfo: {
            /** Description */
            description?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /**
             * Pid
             * @description USB product id as hex string.
             */
            pid?: string | null;
            /**
             * Port
             * @description Stable device path if available, else raw device node.
             */
            port: string;
            /** Product */
            product?: string | null;
            /**
             * Raw Port
             * @description Original pyserial device node (e.g. /dev/ttyACM0).
             */
            raw_port: string;
            /** Serial Number */
            serial_number?: string | null;
            /**
             * Vid
             * @description USB vendor id as hex string (e.g. 0x0403).
             */
            vid?: string | null;
        };
        /**
         * StatsManyResponse
         * @description Batch response for the multi-session stats overlay.
         *
         *     Sessions that are missing at query time (either never existed or were
         *     just closed) are omitted from ``sessions`` — the UI should treat their
         *     absence as "unsubscribe this tile", matching the soft-delete behaviour
         *     of the frontend's `useStreamStats` hook.
         */
        StatsManyResponse: {
            /** Sessions */
            sessions: components["schemas"]["StatsResponse"][];
        };
        /** StatsResponse */
        StatsResponse: {
            /** Entries */
            entries: {
                [key: string]: unknown;
            }[];
            /** Session Id */
            session_id: string;
        };
        /** TeleopCreateRequest */
        TeleopCreateRequest: {
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "keyboard" | "mouse" | "gamepad" | "leader_arm" | "phone";
            /** Name */
            name: string;
        };
        /** TeleopEntry */
        TeleopEntry: {
            /**
             * Config
             * @description Free-form config (key bindings, dead zones, leader-arm port, ...).
             */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "keyboard" | "mouse" | "gamepad" | "leader_arm" | "phone";
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** StopRequest */
        lerobot__dashboard__api__inference__StopRequest: {
            /**
             * Reason
             * @default client
             */
            reason: string;
        };
        /** StopRequest */
        lerobot__dashboard__api__recordings__StopRequest: {
            /**
             * Save
             * @description Finalize the dataset (True) or discard buffered frames (False).
             * @default true
             */
            save: boolean;
        };
        /**
         * StartRequest
         * @description Payload accepted by :meth:`InferenceService.start`.
         *
         *     ``max_action_magnitude`` and ``deadman_required`` are per-session
         *     safety knobs layered on top of adapter-level clamps (e.g. UR's
         *     ``max_relative_target``). The adapter limits stay in place as the
         *     hardware-protection floor; these knobs are the operator's "policy
         *     operating envelope" that can be tightened per run.
         */
        lerobot__dashboard__services__inference__StartRequest: {
            /**
             * Deadman Required
             * @description When True the loop skips ``send_action`` unless the operator is actively holding the deadman (see ``set_deadman``). Dry-run sessions ignore this field.
             * @default false
             */
            deadman_required: boolean;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Fps */
            fps: number;
            /**
             * Max Action Magnitude
             * @description Absolute cap applied to each element of the policy's action vector before ``send_action``. ``None`` means no session-level cap (adapter safety clamps still apply).
             */
            max_action_magnitude?: number | null;
            /** Repo Id */
            repo_id: string;
            /**
             * Robot Id
             * Format: uuid
             */
            robot_id: string;
            /**
             * Task Description
             * @default
             */
            task_description: string;
        };
        /**
         * StartRequest
         * @description Payload accepted by :meth:`RecorderService.start`.
         */
        lerobot__dashboard__services__recorder__StartRequest: {
            /** Dataset Name */
            dataset_name: string;
            /** Fps */
            fps: number;
            /**
             * Robot Id
             * Format: uuid
             */
            robot_id: string;
            /** Task Description */
            task_description: string;
            /**
             * Use Videos
             * @default true
             */
            use_videos: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_benchmarks_endpoint_api_benchmarks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkListResponse"];
                };
            };
        };
    };
    list_runs_api_benchmarks_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunList"];
                };
            };
        };
    };
    start_run_api_benchmarks_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_benchmarks_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_benchmarks_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkRunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cameras_api_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEntry"][];
                };
            };
        };
    };
    create_camera_api_cameras_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_camera_api_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_camera_api_cameras__camera_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_camera_api_cameras__camera_id__open_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_status_api_cameras__camera_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cameras_api_devices_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraDiscoveryResponse"];
                };
            };
        };
    };
    probe_network_api_devices_network_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkProbeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkProbeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_serial_ports_api_devices_serial_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerialDiscoveryResponse"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_inference_sessions_api_inference_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceSession"][];
                };
            };
        };
    };
    start_inference_api_inference_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["lerobot__dashboard__services__inference__StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inference_session_api_inference__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_inference_command_api_inference__session_id__command_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_inference_deadman_api_inference__session_id__deadman_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeadmanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_inference_api_inference__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["lerobot__dashboard__api__inference__StopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InferenceSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_policies_api_policies_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDescriptor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_api_policies__repo_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                repo_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDescriptor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recordings_api_recordings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSession"][];
                };
            };
        };
    };
    start_recording_api_recordings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["lerobot__dashboard__services__recorder__StartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_api_recordings__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_recording_api_recordings__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["lerobot__dashboard__api__recordings__StopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_robots_api_robots_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotEntry"][];
                };
            };
        };
    };
    create_robot_api_robots_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_robot_api_robots__robot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_robot_api_robots__robot_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_robot_api_robots__robot_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ack_calibration_api_robots__robot_id__calibrate_ack_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckAccepted"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_calibration_api_robots__robot_id__calibrate_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationCancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_calibration_api_robots__robot_id__calibrate_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationStartResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConflict"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calibrate_status_api_robots__robot_id__calibrate_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_calibration_api_robots__robot_id__calibration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationConflict"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_robot_api_robots__robot_id__connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disconnect_robot_api_robots__robot_id__disconnect_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_robot_status_api_robots__robot_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                robot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_offer_api_streams_offer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_batch_api_streams_stats_get: {
        parameters: {
            query?: {
                /** @description Optional comma-separated allowlist. When omitted, every active session is returned. */
                session_ids?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsManyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ice_api_streams__session_id__ice_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_keyframe_api_streams__session_id__keyframe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyframeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_quality_api_streams__session_id__quality_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QualityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_streams__session_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_stop_api_streams__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teleops_api_teleops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopEntry"][];
                };
            };
        };
    };
    create_teleop_api_teleops_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeleopCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_teleop_api_teleops__teleop_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teleop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_teleop_api_teleops__teleop_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teleop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_teleop_api_teleops__teleop_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teleop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeleopEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
