"""Camera manager Protocol, in-memory fallback, and lerobot-backed implementation.

The dashboard depends on a single :class:`CameraManagerProtocol` so the HTTP
routes, WebRTC streaming tracks, dataset recorder, and VLA inference can share
one capture loop per camera. Two concrete managers ship here:

* :class:`InMemoryCameraManager` — no-hardware fallback used when the server
  runs with ``fake_devices=True`` or inside unit tests. It fabricates all-zero
  frames at the entry's declared fps.
* :class:`LerobotCameraManager` — wraps :class:`lerobot.cameras.Camera`
  backends (OpenCV / RealSense) behind an async pub/sub hub. One capture task
  per camera pulls frames via :func:`asyncio.to_thread`; every subscriber gets
  a dedicated :class:`asyncio.Queue` with ``maxsize=1`` so the latest frame is
  always immediately available and slow consumers cannot stall the producer.

Streaming consumers (``src/lerobot/dashboard/streaming/``) call
:meth:`CameraManagerProtocol.subscribe` to pull frames; the signature
intentionally mirrors :class:`lerobot.dashboard.streaming.source.FrameSource`
so a thin adapter is all that's needed to bridge the two.

The subscribe-time contract was confirmed with streaming-engineer-3 on
2026-04-14: shared read-only ``ndarray`` (no per-subscriber copy) and no frame
envelope — WebRTC PTS is generated by :class:`LeRobotCameraTrack`.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable
from uuid import UUID

import numpy as np

from lerobot.dashboard.services.registry_models import CameraEntry, CameraStatus
from lerobot.dashboard.streaming.source import FrameSourceError

if TYPE_CHECKING:  # pragma: no cover — avoid heavy imports at module load
    from lerobot.cameras import Camera

logger = logging.getLogger(__name__)

# Sentinel broadcast through a subscriber queue to signal graceful close.
_CLOSE_SENTINEL = object()


@runtime_checkable
class CameraManagerProtocol(Protocol):
    """Live runtime for dashboard-declared cameras."""

    async def open(self, entry: CameraEntry) -> CameraStatus:
        """Acquire hardware handles for ``entry`` and mark it open."""

    async def close(self, camera_id: UUID) -> CameraStatus:
        """Release hardware handles for ``camera_id``."""

    async def is_open(self, camera_id: UUID) -> bool:
        """Return ``True`` if the camera is currently capturing."""

    async def get_status(self, camera_id: UUID) -> CameraStatus:
        """Return the most recent runtime status for ``camera_id``."""

    def subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]:
        """Yield HxWx3 ``uint8`` BGR frames until the subscriber is cancelled.

        Each subscriber gets an independent iterator; dropping the iterator
        (GC or explicit ``aclose``) decrements :attr:`CameraStatus.subscriber_count`.
        """


# ---------------------------------------------------------------------------
# InMemoryCameraManager — fake_devices / unit-test fallback
# ---------------------------------------------------------------------------


@dataclass(slots=True)
class _InMemorySlot:
    status: CameraStatus = field(default_factory=CameraStatus)
    entry: CameraEntry | None = None
    subscribers: int = 0


class InMemoryCameraManager:
    """Fallback :class:`CameraManagerProtocol` that never touches hardware.

    :meth:`subscribe` yields zero-filled frames at the camera's declared fps
    — enough to drive WebRTC negotiation in tests and ``fake_devices`` mode
    without pulling in OpenCV or librealsense.
    """

    def __init__(self) -> None:
        self._lock = asyncio.Lock()
        self._slots: dict[UUID, _InMemorySlot] = {}

    async def open(self, entry: CameraEntry) -> CameraStatus:
        async with self._lock:
            slot = self._slots.setdefault(entry.id, _InMemorySlot())
            slot.entry = entry
            slot.status = CameraStatus(
                online=True,
                last_error=None,
                opened_at=datetime.now(UTC),
                subscriber_count=slot.subscribers,
            )
            return slot.status.model_copy()

    async def close(self, camera_id: UUID) -> CameraStatus:
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is None:
                return CameraStatus()
            slot.status = CameraStatus(
                online=False,
                last_error=slot.status.last_error,
                opened_at=slot.status.opened_at,
                subscriber_count=slot.subscribers,
            )
            return slot.status.model_copy()

    async def is_open(self, camera_id: UUID) -> bool:
        async with self._lock:
            slot = self._slots.get(camera_id)
            return bool(slot and slot.status.online)

    async def get_status(self, camera_id: UUID) -> CameraStatus:
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is None:
                return CameraStatus()
            return slot.status.model_copy(update={"subscriber_count": slot.subscribers})

    async def _increment(self, camera_id: UUID) -> None:
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is not None:
                slot.subscribers += 1

    async def _decrement(self, camera_id: UUID) -> None:
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is not None:
                slot.subscribers = max(0, slot.subscribers - 1)

    async def subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]:
        slot = self._slots.get(camera_id)
        if slot is None or slot.entry is None or not slot.status.online:
            return
        entry = slot.entry
        fps = max(int(entry.fps), 1)
        await self._increment(camera_id)
        try:
            while True:
                slot = self._slots.get(camera_id)
                if slot is None or not slot.status.online:
                    return
                yield np.zeros((entry.height, entry.width, 3), dtype=np.uint8)
                await asyncio.sleep(1.0 / fps)
        finally:
            await self._decrement(camera_id)


# ---------------------------------------------------------------------------
# LerobotCameraManager — real hardware implementation
# ---------------------------------------------------------------------------


CameraBuilder = Callable[[CameraEntry], "Camera"]


def _default_camera_builder(entry: CameraEntry) -> Camera:
    """Build a live :class:`lerobot.cameras.Camera` from a :class:`CameraEntry`.

    Extras such as RealSense depth streams are exposed at the registry level;
    for the dashboard MVP we only surface the color stream.
    """
    from lerobot.cameras import ColorMode
    from lerobot.cameras.utils import make_cameras_from_configs

    if entry.backend == "opencv":
        from lerobot.cameras.opencv import OpenCVCameraConfig

        source = entry.source
        if source.path is not None:
            index_or_path: int | str = source.path
        elif source.index is not None:
            index_or_path = source.index
        else:
            raise ValueError(f"OpenCV camera {entry.id} requires source.path or source.index")
        config = OpenCVCameraConfig(
            index_or_path=index_or_path,  # type: ignore[arg-type]
            fps=int(entry.fps),
            width=entry.width,
            height=entry.height,
            color_mode=ColorMode.BGR,
        )
    elif entry.backend == "realsense":
        from lerobot.cameras.realsense import RealSenseCameraConfig

        if not entry.source.url:
            raise ValueError(f"RealSense camera {entry.id} requires source.url (serial number)")
        config = RealSenseCameraConfig(
            serial_number_or_name=entry.source.url,
            fps=int(entry.fps),
            width=entry.width,
            height=entry.height,
            color_mode=ColorMode.BGR,
        )
    else:
        raise ValueError(f"unsupported camera backend: {entry.backend!r}")

    cameras = make_cameras_from_configs({entry.name: config})
    return cameras[entry.name]


@dataclass
class _LiveSlot:
    entry: CameraEntry
    camera: Camera
    status: CameraStatus
    subscribers: list[asyncio.Queue[Any]] = field(default_factory=list)
    stop_event: asyncio.Event = field(default_factory=asyncio.Event)
    task: asyncio.Task[None] | None = None


class LerobotCameraManager:
    """In-process :class:`CameraManagerProtocol` implementation.

    The manager is thread-safe across asyncio tasks (:class:`asyncio.Lock`
    guards the slot map) but is *not* safe to use from multiple threads — it
    lives inside the FastAPI event loop.
    """

    def __init__(self, camera_builder: CameraBuilder | None = None) -> None:
        self._lock = asyncio.Lock()
        self._slots: dict[UUID, _LiveSlot] = {}
        self._builder: CameraBuilder = camera_builder or _default_camera_builder

    # ----- lifecycle ------------------------------------------------------

    async def open(self, entry: CameraEntry) -> CameraStatus:
        """Instantiate and connect the underlying lerobot camera.

        Idempotent — a second call for an already-open camera returns the
        existing status.
        """
        async with self._lock:
            existing = self._slots.get(entry.id)
            if existing is not None:
                return existing.status.model_copy(
                    update={"subscriber_count": len(existing.subscribers)}
                )
            camera = self._builder(entry)
        try:
            await asyncio.to_thread(camera.connect)
        except Exception as exc:
            logger.exception("camera %s failed to connect", entry.id)
            raise FrameSourceError(f"camera {entry.id} connect failed: {exc}") from exc

        slot = _LiveSlot(
            entry=entry,
            camera=camera,
            status=CameraStatus(online=True, opened_at=datetime.now(UTC)),
        )
        async with self._lock:
            if entry.id in self._slots:
                # Lost a race — tear down the duplicate.
                await asyncio.to_thread(camera.disconnect)
                return self._slots[entry.id].status.model_copy()
            self._slots[entry.id] = slot
            slot.task = asyncio.create_task(
                self._capture_loop(slot),
                name=f"camera-capture-{entry.id}",
            )
            return slot.status.model_copy()

    async def close(self, camera_id: UUID) -> CameraStatus:
        async with self._lock:
            slot = self._slots.pop(camera_id, None)
        if slot is None:
            return CameraStatus()
        slot.stop_event.set()
        if slot.task is not None:
            try:
                await slot.task
            except Exception:  # pragma: no cover — defensive
                logger.exception("capture task for camera %s raised", camera_id)
        for q in list(slot.subscribers):
            _enqueue_drop_oldest(q, _CLOSE_SENTINEL)
        try:
            await asyncio.to_thread(slot.camera.disconnect)
        except Exception:
            logger.exception("disconnect failed for camera %s", camera_id)
        closed = CameraStatus(
            online=False,
            last_error=slot.status.last_error,
            opened_at=slot.status.opened_at,
            subscriber_count=0,
            frames_served=slot.status.frames_served,
        )
        return closed

    async def is_open(self, camera_id: UUID) -> bool:
        async with self._lock:
            slot = self._slots.get(camera_id)
            return bool(slot and slot.status.online)

    async def get_status(self, camera_id: UUID) -> CameraStatus:
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is None:
                return CameraStatus()
            return slot.status.model_copy(update={"subscriber_count": len(slot.subscribers)})

    # ----- subscription ---------------------------------------------------

    def subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]:
        """Return an async iterator over the camera's frames.

        The returned generator registers its queue on first ``__anext__``
        under the manager lock, so a race between close() and subscribe()
        raises :class:`FrameSourceError` rather than hanging forever.
        """
        return self._subscribe(camera_id)

    async def _subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]:
        queue: asyncio.Queue[Any] = asyncio.Queue(maxsize=1)
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is None or not slot.status.online:
                raise FrameSourceError(f"camera {camera_id} is not open")
            slot.subscribers.append(queue)
        try:
            while True:
                item = await queue.get()
                if item is _CLOSE_SENTINEL:
                    return
                if isinstance(item, BaseException):
                    raise item
                yield item  # type: ignore[misc]
        finally:
            async with self._lock:
                slot = self._slots.get(camera_id)
                if slot is not None:
                    try:
                        slot.subscribers.remove(queue)
                    except ValueError:
                        pass

    # ----- capture loop ---------------------------------------------------

    async def _capture_loop(self, slot: _LiveSlot) -> None:
        """Pump frames from the underlying camera into every subscriber."""
        camera = slot.camera
        while not slot.stop_event.is_set():
            try:
                frame = await asyncio.to_thread(_safe_async_read, camera)
            except Exception as exc:
                message = str(exc) or exc.__class__.__name__
                logger.warning("camera %s capture error: %s", slot.entry.id, message)
                slot.status = slot.status.model_copy(update={"online": False, "last_error": message})
                err = FrameSourceError(f"camera {slot.entry.id}: {message}")
                for q in list(slot.subscribers):
                    _enqueue_drop_oldest(q, err)
                return
            if frame is None:
                # Backend returned no new frame (stale timeout); try again.
                continue
            for q in list(slot.subscribers):
                _enqueue_drop_oldest(q, frame)
            slot.status = slot.status.model_copy(
                update={"frames_served": slot.status.frames_served + 1}
            )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _enqueue_drop_oldest(queue: asyncio.Queue[Any], item: Any) -> None:
    """Put ``item`` on the bounded queue, discarding the oldest on overflow."""
    if queue.full():
        try:
            queue.get_nowait()
        except asyncio.QueueEmpty:
            pass
    try:
        queue.put_nowait(item)
    except asyncio.QueueFull:  # pragma: no cover — race with another producer
        pass


def _safe_async_read(camera: Camera) -> np.ndarray | None:
    """Wrapper that calls ``camera.async_read`` with the SDK's default timeout.

    :class:`lerobot.cameras.Camera` defines ``async_read(timeout_ms=...)`` so
    we let each backend choose its own default. Some backends return ``None``
    when no new frame has arrived — the capture loop treats that as a benign
    retry.
    """
    return camera.async_read()


__all__ = [
    "CameraManagerProtocol",
    "CameraStatus",
    "InMemoryCameraManager",
    "LerobotCameraManager",
]
