"""Live-camera manager implementing :class:`CameraManagerProtocol`.

Wraps :class:`lerobot.cameras.Camera` backends (OpenCV / RealSense) behind a
single async pub/sub hub so multiple consumers — WebRTC tracks, dataset
recorders, VLA inference — can share a single capture loop per camera.

Design
------
* One *capture task* per opened camera pulls frames via
  ``camera.async_read`` (called off-loop with :func:`asyncio.to_thread`).
* Each subscriber gets a dedicated :class:`asyncio.Queue` with ``maxsize=1``
  so the latest frame is always immediately available; older unread frames
  are dropped so slow consumers don't stall the producer.
* :meth:`LerobotCameraManager.subscribe` returns an async generator.
  - Graceful :meth:`close` sends a ``None`` sentinel → ``StopAsyncIteration``.
  - Fatal capture failure raises :class:`lerobot.dashboard.streaming.source.FrameSourceError`
    on the subscriber side so the streaming track can fall back to its
    last-good cache (see :mod:`lerobot.dashboard.streaming.source`).

The subscribe-time contract was confirmed with streaming-engineer-3 on
2026-04-14: shared read-only ``ndarray`` (no per-subscriber copy) and
no frame envelope — WebRTC PTS is generated by :class:`LeRobotCameraTrack`.
"""

from __future__ import annotations

import asyncio
import logging
from collections.abc import AsyncIterator, Callable
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable
from uuid import UUID

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

from lerobot.dashboard.services.registry_models import CameraEntry
from lerobot.dashboard.streaming.source import FrameSourceError

if TYPE_CHECKING:  # pragma: no cover — avoid heavy imports at module load
    from lerobot.cameras import Camera

logger = logging.getLogger(__name__)

# Sentinels broadcast through the subscriber queue.
_CLOSE_SENTINEL = object()


class CameraStatus(BaseModel):
    """Runtime status of an open camera. Not persisted to the registry."""

    model_config = ConfigDict(extra="forbid")

    online: bool = False
    opened_at: datetime | None = None
    last_error: str | None = None
    frames_served: int = Field(default=0, ge=0)
    subscriber_count: int = Field(default=0, ge=0)


@runtime_checkable
class CameraManagerProtocol(Protocol):
    """Contract consumed by streaming, dataset-recording, and VLA layers."""

    async def open(self, entry: CameraEntry) -> None: ...
    async def close(self, camera_id: UUID) -> None: ...
    async def is_open(self, camera_id: UUID) -> bool: ...
    def subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]: ...
    async def get_status(self, camera_id: UUID) -> CameraStatus: ...


CameraBuilder = Callable[[CameraEntry], "Camera"]


# ---------------------------------------------------------------------------
# Default CameraEntry -> lerobot.cameras.Camera builder
# ---------------------------------------------------------------------------


def _default_camera_builder(entry: CameraEntry) -> Camera:
    """Build a live :class:`lerobot.cameras.Camera` from a :class:`CameraEntry`.

    Extras such as RealSense depth streams are exposed at the registry
    level; for the dashboard MVP we only surface the color stream.
    """
    from lerobot.cameras import ColorMode
    from lerobot.cameras.utils import make_cameras_from_configs

    if entry.backend == "opencv":
        from lerobot.cameras.opencv import OpenCVCameraConfig

        source = entry.source
        if source.path is not None:
            index_or_path: int | str = source.path
        elif source.index is not None:
            index_or_path = source.index
        else:
            raise ValueError(f"OpenCV camera {entry.id} requires source.path or source.index")
        config = OpenCVCameraConfig(
            index_or_path=index_or_path,  # type: ignore[arg-type]
            fps=int(entry.fps),
            width=entry.width,
            height=entry.height,
            color_mode=ColorMode.BGR,
        )
    elif entry.backend == "realsense":
        from lerobot.cameras.realsense import RealSenseCameraConfig

        if not entry.source.url:
            raise ValueError(f"RealSense camera {entry.id} requires source.url (serial number)")
        config = RealSenseCameraConfig(
            serial_number_or_name=entry.source.url,
            fps=int(entry.fps),
            width=entry.width,
            height=entry.height,
            color_mode=ColorMode.BGR,
        )
    else:
        raise ValueError(f"unsupported camera backend: {entry.backend!r}")

    cameras = make_cameras_from_configs({entry.name: config})
    return cameras[entry.name]


# ---------------------------------------------------------------------------
# Internal slot
# ---------------------------------------------------------------------------


@dataclass
class _CameraSlot:
    entry: CameraEntry
    camera: Camera
    status: CameraStatus
    subscribers: list[asyncio.Queue[Any]] = field(default_factory=list)
    stop_event: asyncio.Event = field(default_factory=asyncio.Event)
    task: asyncio.Task[None] | None = None


# ---------------------------------------------------------------------------
# LerobotCameraManager
# ---------------------------------------------------------------------------


class LerobotCameraManager:
    """In-process :class:`CameraManagerProtocol` implementation.

    The manager is thread-safe across asyncio tasks (:class:`asyncio.Lock`
    guards the slot map) but is *not* safe to use from multiple threads —
    it lives inside the FastAPI event loop.
    """

    def __init__(self, camera_builder: CameraBuilder | None = None) -> None:
        self._lock = asyncio.Lock()
        self._slots: dict[UUID, _CameraSlot] = {}
        self._builder: CameraBuilder = camera_builder or _default_camera_builder

    # ----- lifecycle ------------------------------------------------------

    async def open(self, entry: CameraEntry) -> None:
        """Instantiate and connect the underlying lerobot camera.

        Idempotent — a second call for an already-open camera is a no-op.
        """
        async with self._lock:
            if entry.id in self._slots:
                return
            camera = self._builder(entry)
        try:
            await asyncio.to_thread(camera.connect)
        except Exception as exc:
            logger.exception("camera %s failed to connect", entry.id)
            raise FrameSourceError(f"camera {entry.id} connect failed: {exc}") from exc

        slot = _CameraSlot(
            entry=entry,
            camera=camera,
            status=CameraStatus(online=True, opened_at=datetime.now(UTC)),
        )
        async with self._lock:
            if entry.id in self._slots:
                # Lost a race — tear down the duplicate.
                await asyncio.to_thread(camera.disconnect)
                return
            self._slots[entry.id] = slot
            slot.task = asyncio.create_task(
                self._capture_loop(slot),
                name=f"camera-capture-{entry.id}",
            )

    async def close(self, camera_id: UUID) -> None:
        async with self._lock:
            slot = self._slots.pop(camera_id, None)
        if slot is None:
            return
        slot.stop_event.set()
        if slot.task is not None:
            try:
                await slot.task
            except Exception:  # pragma: no cover — defensive
                logger.exception("capture task for camera %s raised", camera_id)
        for q in list(slot.subscribers):
            _enqueue_drop_oldest(q, _CLOSE_SENTINEL)
        try:
            await asyncio.to_thread(slot.camera.disconnect)
        except Exception:
            logger.exception("disconnect failed for camera %s", camera_id)

    async def is_open(self, camera_id: UUID) -> bool:
        async with self._lock:
            slot = self._slots.get(camera_id)
            return bool(slot and slot.status.online)

    async def get_status(self, camera_id: UUID) -> CameraStatus:
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is None:
                return CameraStatus()
            return slot.status.model_copy(update={"subscriber_count": len(slot.subscribers)})

    # ----- subscription ---------------------------------------------------

    def subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]:
        """Return an async iterator over the camera's frames.

        The returned generator registers its queue on first ``__anext__``
        under the manager lock, so a race between close() and subscribe()
        raises :class:`FrameSourceError` rather than hanging forever.
        """
        return self._subscribe(camera_id)

    async def _subscribe(self, camera_id: UUID) -> AsyncIterator[np.ndarray]:
        queue: asyncio.Queue[Any] = asyncio.Queue(maxsize=1)
        async with self._lock:
            slot = self._slots.get(camera_id)
            if slot is None or not slot.status.online:
                raise FrameSourceError(f"camera {camera_id} is not open")
            slot.subscribers.append(queue)
        try:
            while True:
                item = await queue.get()
                if item is _CLOSE_SENTINEL:
                    return
                if isinstance(item, BaseException):
                    raise item
                yield item  # type: ignore[misc]
        finally:
            async with self._lock:
                slot = self._slots.get(camera_id)
                if slot is not None:
                    try:
                        slot.subscribers.remove(queue)
                    except ValueError:
                        pass

    # ----- capture loop ---------------------------------------------------

    async def _capture_loop(self, slot: _CameraSlot) -> None:
        """Pump frames from the underlying camera into every subscriber."""
        camera = slot.camera
        while not slot.stop_event.is_set():
            try:
                frame = await asyncio.to_thread(_safe_async_read, camera)
            except Exception as exc:
                message = str(exc) or exc.__class__.__name__
                logger.warning("camera %s capture error: %s", slot.entry.id, message)
                slot.status.online = False
                slot.status.last_error = message
                err = FrameSourceError(f"camera {slot.entry.id}: {message}")
                for q in list(slot.subscribers):
                    _enqueue_drop_oldest(q, err)
                return
            if frame is None:
                # Backend returned no new frame (stale timeout); try again.
                continue
            for q in list(slot.subscribers):
                _enqueue_drop_oldest(q, frame)
            slot.status.frames_served += 1


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _enqueue_drop_oldest(queue: asyncio.Queue[Any], item: Any) -> None:
    """Put ``item`` on the bounded queue, discarding the oldest on overflow."""
    if queue.full():
        try:
            queue.get_nowait()
        except asyncio.QueueEmpty:
            pass
    try:
        queue.put_nowait(item)
    except asyncio.QueueFull:  # pragma: no cover — race with another producer
        pass


def _safe_async_read(camera: Camera) -> np.ndarray | None:
    """Wrapper that calls ``camera.async_read`` with the SDK's default timeout.

    :class:`lerobot.cameras.Camera` defines ``async_read(timeout_ms=...)`` so
    we let each backend choose its own default. Some backends return
    ``None`` when no new frame has arrived — the capture loop treats that
    as a benign retry.
    """
    return camera.async_read()


__all__ = [
    "CameraManagerProtocol",
    "CameraStatus",
    "LerobotCameraManager",
]
